dataset: "LTS"

path:
  corpus_path: "data\\Dataset\\LTS\\LibriTTS"
  wav_tag: "mic1"
  wav_dir: "test-clean"
  txt_dir: "test-clean"
  lexicon_path: "lexicon\\librispeech-lexicon.txt"
  raw_path: "raw_data\\LTS"
  preprocessed_path: "preprocessed_data\\LTS"

  in_dir : "C:\\Bryan\\Code\\Comprehensive-Transformer-TTS\\raw_data\\LTS"
  text_grid_dir: "C:\\Bryan\\Code\\Comprehensive-Transformer-TTS\\preprocessed_data\\LTS\\TextGrid"
  save_dir: "C:\\Bryan\\Code\\Vicuna\\data"

token:
  pitch: "$"
  duration: "%"
  window_time: 0.5

#   corpus_path: "data\\Dataset\\LibriTTS"
#   wav_tag: "mic1"
#   wav_dir: "dev-clean"
#   txt_dir: "dev-clean"
#   lexicon_path: "lexicon\\librispeech-lexicon.txt"
#   raw_path: "raw_data\\LTSdev"
#   preprocessed_path: "preprocessed_data\\LTSdev"

preprocessing:
  # speaker_embedder: "Encoder" # support 'none', 'DeepSpeaker', "Encoder"
  # speaker_embedder_path: "./encoder/pretrained_models/encoder.pt"
  # speaker_embedder_cuda: False # since it's too large to load in a single GPU
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    trim_top_db: 23
    sampling_rate: 24000
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    pitch_type: "cwt" # support 'frame', 'ph', 'cwt'
    pitch_norm: "log" # support 'standard', 'log'
    pitch_norm_eps: 0.000000001
    pitch_ar: False
    with_f0: True
    with_f0cwt: True
    use_uv: True
    cwt_scales: -1
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  duration:
    beta_binomial_scaling_factor: 1.0
